Add created at and updated at fields
fivetran/dbt_quickbooks pull request #146
Opened 2024-11-18 16:27 UTC by fivetran-avinash

## PR Overview
**This PR will address the following Issue/Feature:**

**This PR will result in the following new package version:**

**Please provide the finalized CHANGELOG entry which details the relevant changes included in this PR:**

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [ ] dbt run –full-refresh && dbt test
- [ ] dbt run (if incremental models are present) && dbt test

Before marking this PR as "ready for review" the following have been applied:
- [ ] The appropriate issue has been linked, tagged, and properly assigned
- [ ] All necessary documentation and version upgrades have been applied
- [ ] docs were regenerated (unless this PR does not include any code or yml updates)
- [ ] BuildKite integration tests are passing
- [ ] Detailed validation steps have been provided below

### Detailed Validation
Please share any and all of your validation steps:

### If you had to summarize this PR in an emoji, which would it be?
 
:dancer:

2024-11-20 23:15 UTC, fivetran-joemarkiewicz requested changes
@fivetran-avinash this is looking great! I just have a few small requests and one small question before approving.

2024-11-21 21:36 UTC, fivetran-avinash commented on integration_tests/dbt_project.yml
> +version: '0.17.0'
This must be an artifact from testing on seed data. Removing from the actual model.

2024-11-21 21:48 UTC, fivetran-avinash commented on README.md
> +    version: [">=0.17.0", "<0.18.0"] # we recommend using ranges to capture non-breaking changes automatically
Updated

2024-11-21 21:48 UTC, fivetran-avinash commented on packages.yml
> +    warn-unpinned: false
```suggestion
  - package: fivetran/quickbooks_source
    version: [">=0.12.0", "<0.13.0"]
```

2024-11-21 22:08 UTC, fivetran-avinash commented on CHANGELOG.md
> +- This isn't necessarily a breaking change, but as this introduces new fields to an end model, we determined it was best to bump the version up.
Removed

2024-11-21 22:08 UTC, fivetran-avinash commented on packages.yml
> +    warn-unpinned: false
Added a suggestion reminder

2024-11-21 22:08 UTC, fivetran-avinash reviewed
@fivetran-joemarkiewicz This is ready for re-review.

2024-11-21 22:55 UTC, fivetran-joemarkiewicz approved these changes
LGTM

2024-11-22 22:42 UTC, fivetran-catfritz reviewed
@fivetran-avinash a couple comments/questions!

2024-11-22 22:42 UTC, fivetran-catfritz commented on CHANGELOG.md
> +- We have introduced the following fields in the `quickbooks__general_ledger` to better analyze real-time transaction data:
```suggestion
- Introduced the following fields in the `quickbooks__general_ledger` model to better analyze real-time transaction data:
```

2024-11-22 22:42 UTC, fivetran-catfritz commented on CHANGELOG.md
> +- This is a breaking change as this adds new fields to the existing schema for one of our end models.
```suggestion
- This is a breaking change as this adds new fields to the existing schema. 
```

2024-11-22 22:42 UTC, fivetran-catfritz commented on CHANGELOG.md
> +  - This required updates to all our double entry transaction models to bring in these specific fields for each transaction type.
```suggestion
  - Updated the `*_double_entry` models to add these fields for each transaction type.
```

2024-11-22 22:42 UTC, fivetran-catfritz commented on models/intermediate/int_quickbooks__retained_earnings.sql
> +
Can you explain these changes in the changelog? It's just not obviously related to the created/update_at if it's part of those changes.

2024-11-25 20:42 UTC, fivetran-avinash commented on CHANGELOG.md
> +- We have introduced the following fields in the `quickbooks__general_ledger` to better analyze real-time transaction data:
Committed!

2024-11-25 20:42 UTC, fivetran-avinash commented on CHANGELOG.md
> +- This is a breaking change as this adds new fields to the existing schema for one of our end models.
Changed.

2024-11-25 20:42 UTC, fivetran-avinash commented on CHANGELOG.md
> +  - This required updates to all our double entry transaction models to bring in these specific fields for each transaction type.
Updated.

2024-11-25 20:51 UTC, fivetran-avinash reviewed
@fivetran-catfritz Addressed your comments!

2024-11-25 21:42 UTC, fivetran-catfritz commented on models/intermediate/int_quickbooks__retained_earnings.sql
> +
Got it. I'll leave it to your judgement!

2024-11-25 21:42 UTC, fivetran-catfritz approved these changes
@fivetran-avinash lgtm!

2024-11-26 07:38 UTC, merged