[Pre-release v2] Bug fix for net income adjustment for no revenue/expense lines
fivetran/dbt_quickbooks pull request #149
Opened 2024-12-10 16:15 UTC by fivetran-avinash

This is a PR branch to validate a potential fix for issue #145. We cut an earlier version of this release but Quickstart was not able to pick it up, so we are creating a new branch to do that.

2024-12-10 16:32 UTC, fivetran-joemarkiewicz reviewed
Not approving yet since this is not intended to be merged as of this moment. However, this is appropriate to cut a pre-release off for v0.17.1-a1

2024-12-17 06:51 UTC, fivetran-avinash commented
This is now ready for official PR review.

2024-12-18 20:52 UTC, fivetran-joemarkiewicz requested changes
These changes look good to me. However, I noticed not related to these changes, but in [this update](https://github.com/fivetran/dbt_quickbooks/pull/146) we didn't bring the `created_at` and `updated_at` fields into the final invoice double entry query (see [here](https://github.com/fivetran/dbt_quickbooks/blob/69b8e22e330a915e58d312f718ba6c4720ba0fec/models/double_entry_transactions/int_quickbooks__invoice_double_entry.sql#L136-L137)). Can you please add those into this update as well.

2024-12-19 17:01 UTC, fivetran-avinash reviewed
@fivetran-joemarkiewicz Changes applied. Ready for re-review

2024-12-23 20:06 UTC, fivetran-joemarkiewicz approved these changes
LGTM

2024-12-30 22:02 UTC, fivetran-jamie approved these changes
LGTM

2025-01-06 21:05 UTC, merged